server:
  port: 8090
  use-forward-headers: true
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: admin

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapperLocations: classpath:com/nongshanie/springboot/springbootdemo/dao/mapper/*.xml
  typeAliasesPackage: com.nongshanie.springboot.springbootdemo.dao
logging:
  file: ./logs/log.log


